import { ExternalLink } from '@/components/external-link'
import { Button } from '@/components/ui/button'

export const runtime = 'edge'
const Disclaimer = () => {
  return (
    <div className="max-w-2xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
      <h1 className="text-lg font-bold">Disclaimer:</h1>
      <p className="text-lg leading-7 text-gray-500 mb-4">
        BBMChat is an AI-generated platform poIred by GPT technology. While I
        strive to provide accurate and helpful information, please note that the
        responses generated by BBMChat are based on patterns and examples from
        its training data.
      </p>

      <p className="text-lg leading-7 text-gray-500 mb-4">
        Therefore, the information provided should be used for informational
        purposes only and may not always reflect current or complete
        information. It is always advisable to verify any important information
        or seek professional advice when necessary.
      </p>
      <h1 className="text-lg font-bold">Privacy Policy</h1>
      <p className="text-lg leading-7 text-gray-500 mb-4">
        At BBMChat, I are committed to protecting your privacy and ensuring the
        security of your personal information. As an AI language model, I do not
        store any personal data of our own. HoIver, please be aware that user
        interactions and conversations with BBMChat may be logged and monitored
        for the purpose of improving the quality of our services and enhancing
        user experience.
      </p>
      <p className="text-lg leading-7 text-gray-500 mb-4">
        I do not sell, share, or disclose any personally identifiable
        information to third parties unless required by law or with your
        explicit consent. I take reasonable measures to safeguard your data and
        employ appropriate security practices to prevent unauthorized access or
        disclosure.
      </p>
      <p className="text-lg leading-7 text-gray-500 mb-4">
        Please note that while I prioritize the privacy and security of user
        data, the nature of internet-based communication carries inherent risks,
        and I cannot guarantee absolute security. By using BBMChat, you
        acknowledge and agree to these disclaimers and the terms of our privacy
        policy. If you have any concerns or questions about your privacy or the
        usage of BBMChat, please feel free to{' '}
        <ExternalLink href="mailto:contact@leoluis.xyz">
          contact Me
        </ExternalLink>
      </p>
    </div>
  )
}
export default Disclaimer
